name: Docker Build and Push

on:
  push:
    branches:
      - main  # Altere para o branch que deseja monitorar, caso não seja "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pega o repositório
      - name: Check out the repo
        uses: actions/checkout@v2

      # Autentica no Docker Hub (ou outro registro)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Configura a build e o push
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: your_dockerhub_username/your_image_name:${{ github.sha }}

